### ISSUE TITLE
throwing custom errors

### ISSUE THREAD

**Issue by sckott** [Ironholds/piton#1]
@Ironholds played at all yet with throwing custom errors?

trying to sort out how to instead of simply erroring when a rule doesn't match, throw a warning or so, and return e.g., `NA` or similar 

not clear to me where to place error catching yet. in the grammar definition? in the individual rules that go into the grammar? somewhere else?

**Comment by sckott** [comment]
the docs do have https://github.com/taocpp/PEGTL/blob/master/doc/Errors-and-Exceptions.md#custom-exception-messages  but not sure how to use it yet

**Comment by nacnudus** [comment]
My approach would have been to raise errors in actions, but apparently that isn't supported https://github.com/taocpp/PEGTL/issues/69.

**Comment by skyrich62** [comment]
You can absolutely raise errors in actions.  You catch them in the grammar by adding a pegtl::try_catch<>.
try_catch<> will catch only things derived from pegtl::parse_error, so if you want to catch anything else, you must use: try_catch_type<x, ...>  The examples from the website posted by @sckott, so using must<> in the grammar to automatically throw a parse_error.

What you are attempting to do here, I think is not just custom error messages and throwing, but *recovering* from a parse error, which is a tricky thing.  This must also be implemented in the grammar.

This may help: https://github.com/taocpp/PEGTL/issues/55
